export const SET_VIEW = 'SET_VIEW';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';

export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';

export const PRODUCT_DETAIL_FETCH_START = 'PRODUCT_DETAIL_FETCH_START';
export const PRODUCT_DETAIL_FETCH_SUCCESS = 'PRODUCT_DETAIL_FETCH_SUCCESS';
export const PRODUCT_DETAIL_FETCH_FAIL = 'PRODUCT_DETAIL_FETCH_FAIL';
export const HANDLE_ADDED_TO_CART = 'HANDLE_ADDED_TO_CART';

export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const PLACE_ORDER = 'PLACE_ORDER';
