export const SET_VIEW = 'SET_VIEW';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';

export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL';
