export const ac = [
  'apica',
  'aston leather',
  'aurora',
  'benu',
  'clairefontaine',
  'colorverse',
  'conklin',
];
export const df = [
  'david oscarson',
  'de atramentis',
  'diamine',
  'diplomat',
  'editson',
  'endless works',
  'esterbrook',
  'exacompta',
  'field notes',
  'franklin-christoph',
];
export const gk = [
  'g. lalo',
  'galen leather',
  'girologio',
  'goulet',
  'herbin',
  'herbert pen company',
  'ink miser',
  'jacque herbin',
  'jinhao',
  'kaweco',
];
export const ln = [
  'lamy',
  'leuchtturm 1979',
  'maiora',
  'maruman mnemosyne',
  'montegrappa',
  'monteverde',
  'namiki',
  'nebula',
  'nettuno',
  "noodler's",
];
export const op = [
  'opus 88',
  'organics studio',
  'original crown mill',
  'pelikan',
  'penlux',
  'pilot',
  'pineider',
  'platinum',
  'private reserve',
];
export const qs = [
  'quo vadis',
  'retro 51',
  'rhodia',
  'rickshaw bagworks',
  'robert oster',
  'rohrer & klingner',
  'sailor',
  's.t. dupont',
  'stipula',
];
export const tz = [
  'taccia',
  'tibaldi',
  'tomoe river',
  "traveler's company",
  'twsbi',
  'visconti',
  'yonkers',
  'ystudio',
];
